### ISSUE TITLE
same Height not working in version pro

### ISSUE THREAD

**Issue by eavalencia86** [dudaster/ele-custom-skin#697] opened 2022-02-23 14:25 UTC
Hello I bought the pro version today and "same height" does not work.
Create a loop template, but it doesn't work with the "sam height" function.

example error: https://ibb.co/6m2D5cS

thanks!

**Comment by AzTeK23** [comment] 2022-02-23 17:58
WP 5.9.1 / ECS 3.1.4 / ECS Pro 3.2.2

Hi,

Getting the same issue. I'm using post widget calling a custom template : the displayed elements are completely offset. 
It was working fine before the last update was applied: deactivating / reactivating the "same height" option does not change anything (as you suggest in the update log).

I had to disable this option on many page templates, which is very annoying...

Best regards

**Comment by djaysan** [comment] 2022-02-24 00:42
Hi! when equal height is enabled, using inner sections within the loop breaks the layout.

Thanks to @mmcgowan1 
I've discovered that if you have an inner section within the loop -- in my case to display two columns -- it breaks the post display, if "equal height" is turned on. The feature works if there is only one section in the post loop. This is a change in behavior because it worked fine with inner sections before.

**Comment by AaronTriQ** [comment] 2022-02-24 09:06
I'm having the same problem as djaysan with the latest update.

**Comment by dudaster** [comment] 2022-02-24 09:55
Please make sure you check and uncheck same height feature and it should fix the issu

**Comment by AzTeK23** [comment] 2022-02-24 10:14
I've done it several times - again just now to be nice to you ;) - and it always triggers the default.

**Comment by LPAWEB** [comment] 2022-02-24 10:39
Your solution of deactivating and activating the same height does not work, no matter how many times I try, when activating it again the whole design is unbalanced, it happens to me on more than 20 websites with different themes and plugins, so it is not incompatibility with them ... I must keep it off for the layout to stay...

**Comment by dudaster** [comment] 2022-02-24 10:53
You have installed Ele custom skin pro 3.2.2?

**Comment by djaysan** [comment] 2022-02-24 10:56
> Please make sure you check and uncheck same height feature and it should fix the issu

I confirm checking and unchecking same height does not work does not work. it's when I have inner sections in the loop template

**Comment by dudaster** [comment] 2022-02-24 10:57
I will try it on my end.

**Comment by AaronTriQ** [comment] 2022-02-24 10:57
Unchecking and checking didn't work for me either. Problem is fixed by rolling back to 3.1.0 and resaving my pages for now.

**Comment by LPAWEB** [comment] 2022-02-24 11:11
> You have installed Ele custom skin pro 3.2.2?

Yes, in all webs I have installed pro 3.2.2

**Comment by dudaster** [comment] 2022-02-24 11:12
Can you export and attach here your loop template?

**Comment by LPAWEB** [comment] 2022-02-24 11:19
> Can you export and attach here your loop template?
[elementor-212-2022-02-24.zip](https://github.com/dudaster/ele-custom-skin/files/8132051/elementor-212-2022-02-24.zip)
>

**Comment by LPAWEB** [comment] 2022-02-25 11:52
The same height definitely does not work, any solution?

**Comment by dudaster** [comment] 2022-02-25 11:56
Make sure you have only one main section inside the loop teplate, add a  background to it and see if it is working. To distribute the content you can set the main section to min height and then you'll have the option to add equal height between elements. I'll try to make this weekend a mini tutorial.

This issue is for the users who got it working in the past but is not working now anymore.

**Comment by dudaster** [comment] 2022-02-25 11:58
> > Can you export and attach here your loop template?
> > [elementor-212-2022-02-24.zip](https://github.com/dudaster/ele-custom-skin/files/8132051/elementor-212-2022-02-24.zip)

Thanks for the template. I was able to see what the issue is. An update would be available ASAP.

**Comment by JeremyRAlexander** [comment] 2022-02-25 20:25
I am having the same issue as everyone else. Thanks for working on an update asap. I have sections inside the loop template in order to make groupings of information work properly.

**Comment by umm-wdc** [comment] 2022-02-28 11:52
+1 facing the same issue on all our client sites. Hope the update will be released soon. Thanks in advance @dudaster

**Comment by asleepfromday** [comment] 2022-03-02 00:35
@dudaster  any update yet?  I have so many client sites that do not work properly now.

**Comment by KK708809** [comment] 2022-03-08 04:08
@dudaster - Any update to this issue? , Literally just paid for the pro version for this function, and it's not working .

**Comment by asleepfromday** [comment] 2022-03-08 11:22
> @dudaster - Any update to this issue? , Literally just paid for the pro version for this function, and it's not working .

previously he has been very quick to fix stuff. Hopefully he is all good and can get us a fix soon.

**Comment by Overbord** [comment] 2022-03-11 07:52
Same issue.

**Comment by 8persap** [comment] 2022-03-15 11:27
Hi there. Same problem. Pretty much broken 3 important repositories on a client site. They are p***ed! Seems like a lot of people are facing this equal height issue. 18 days since dev replied. Please can we have an update one way or the other, so we can set expectations with clients. Thanks.

**Comment by 8persap** [comment] 2022-03-15 11:28
Also, where can we get previous version of pro to use for now while a fixed is being worked on, please?

**Comment by dudaster** [comment] 2022-03-15 11:29
The fix would be released tommorow.

**Comment by 8persap** [comment] 2022-03-15 11:30
Thanks. Where can I get a previous version of pro for now, please?

**Comment by LPAWEB** [comment] 2022-03-15 11:38
and in addition to having more than 30 sites deconfigured during all this time, I will always be left with the doubt of how many potential clients I may have lost if someone got into my portfolio and saw the broken sites .... fantastic!

**Comment by AzTeK23** [comment] 2022-03-17 10:21
Hi! The patch published today fixes the issue: thanks!

**Comment by KK708809** [comment] 2022-03-17 21:08
@dudaster - Updated the patch - Toggle the same height on and off again but doesn't work still?

**Comment by Mariedel2** [comment] 2022-03-22 10:54
Hi, updating to 3.2.3 has not fixed the issue for me - any other solutions?

**Closed as completed** 2022-05-18 08:37 UTC
