### ISSUE TITLE
Same Height is not working - Pro Version

### ISSUE THREAD

**Issue by ManuelRomeroLA** [dudaster/ele-custom-skin#649] opened 2022-01-04 21:26 UTC
Hello. On my site at https://devths.wpengine.com/for-parents/ - Parent Tool section, the cards are not equal height.  Please let me know how to fix this.

**Comment by puregraphx** [comment] 2022-02-03 10:41
duplicate of #630

**Closed as completed** 2022-05-18 08:37 UTC
