### ISSUE TITLE
Unable to select newly created loop

### ISSUE THREAD

**Issue by ScienceNordic** [dudaster/ele-custom-skin#50] opened 2019-08-30 05:01 UTC
Hi, I have just downloaded the Ele Custom Skin plug in, activated it, and created my first loop template. When I go to the page in which I want to display the customised post skins, I can select "custom", I can search for my new loop template in the posts widget, but when I click to select it nothing happens. While I can see the new loop template in the drop down list, I cannot select it. I'm running Elementor Pro 2.6.5 on a GeneratePress theme. Any ideas?

**Comment by dudaster** [comment] 2019-08-30 05:04
I’m not sure. Can you provide me an error? Try create a simple template and see if that works. Are you using multilanguage?

**Comment by dudaster** [comment] 2019-08-30 05:38
Also, what browser are you using?

**Comment by dudaster** [comment] 2019-08-30 05:57
Ok I think I know what the issue is. I think I reproduced it myself in Safari with only one Loop Template. It seems it is an Elementor Select Control issue if, you have only one item in the select in Safari is not working. 

How to fix it:
Make sure you have at least 2 Loop Templates if you're using Safari browser.
Use another browser.

I'll try to talk with Elementor support to see how this can be fixed.

Thanks for report!

**Comment by ScienceNordic** [comment] 2019-08-30 14:45
Thanks! That worked. :-)

**Comment by dudaster** [comment] 2019-09-19 15:35
Issue is fixed with the latest ECS

**Closed as completed by dudaster** 2019-09-19 15:35 UTC
