### ISSUE TITLE
Filter with masonry don't work

### ISSUE THREAD

**Issue by ELSENO** [dudaster/ele-custom-skin#224] opened 2020-06-04 11:30 UTC
The masonry style don't work with filters. We use a custom loop template.
Any suggestion how to fix? :)

[http://stadtlabor.elsenoserver.at/altstadt/](http://stadtlabor.elsenoserver.at/altstadt/)

Ele Custom Skin 2.2.1
Ele Custom Skin Pro 2.1.0
Elementor 2.9.11
Elementor Pro 2.9.5
Elementor SuperCat 2.5.2 (for filter function)

**Comment by dudaster** [comment] 2020-06-04 18:08
when ajax is loaded you can use this js function to reinstate the masonry and make post clickable from ECS:

`ECS_do_action('ajax');`

**Comment by dudaster** [comment] 2020-06-04 18:09
Duplicate of #220

**Closed as completed** 2020-06-11 13:53 UTC
