### ISSUE TITLE
Featured image fallback bug inside a loop

### ISSUE THREAD

**Issue by DODMax** [dudaster/ele-custom-skin#139] opened 2020-01-20 09:22 UTC
Hello,

When using a featured image as a background inside a loop, the fallback is not used properly.
![image](https://user-images.githubusercontent.com/1137276/72714186-e0c47900-3ba0-11ea-95f2-ca842b3dc68f.png)

Posts without featured images end up with the first featured image of the loop (or so it seems) instead of the fallback.

Thanks,

**Comment by dudaster** [comment] 2020-01-20 14:13
I'll take a look

**Comment by dudaster** [comment] 2020-01-20 14:35
Please provide me an URL so I can inspect element. I can't reproduce it on my end.

**Comment by DODMax** [comment] 2020-01-23 06:29
You can see it happening here: https://1d.lexiconthai.dev/blog/
The post order is random but whichever comes first will be used as fallback image (and if first has no featured image then no fallback). The setting of the loop can be seen on my screenshot above.

**Comment by dudaster** [comment] 2020-01-23 06:53
This is what I'm seeing:
![Capture](https://user-images.githubusercontent.com/8319178/72962745-e0ed9000-3dbd-11ea-884c-643c22c0d780.JPG)

**Comment by dudaster** [comment] 2020-01-23 07:01
I think I see it... I'll try to reproduce it and let you know my progress.

**Comment by dudaster** [comment] 2020-01-23 07:14
If you are in a hurry for a fix give a class to the section with the background in Loop Template, let say: `.fimage` and create a custom css in the Posts (Archive) Widget that sounds like this: `.fimage 
 .elementor-column-wrap{background-image: url(/wp-content/uploads/2019/08/Group-3.png);}`
You get the idea!

**Comment by dudaster** [comment] 2020-03-24 14:32
fixed with the new update

**Closed as completed by dudaster** 2020-03-24 14:33 UTC
